# @name login
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
  "email": "teste@gmail.com",
  "password": "123456"
}

@token = {{login.response.body.data.token}}

###
POST http://localhost:8080/menu/category/44444444-4444-4444-4444-444444444444/item HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Coca-cola",
  "description": "Refrigerante sabor cola",
  "base_price": 500,
  "is_active": true
}

###
GET http://localhost:8080/menu/category/item/66666666-6666-6666-6666-666666666666 HTTP/1.1
Authorization: Bearer {{token}}

###
GET http://localhost:8080/menu/category/items/44444444-4444-4444-4444-444444444444 HTTP/1.1
Authorization: Bearer {{token}}
