# @name login
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
  "email": "teste@gmail.com",
  "password": "123456"
}

@token = {{login.response.body.data.token}}

###
POST http://localhost:8080/menu/906809e1-25ae-40ce-91d5-af90313868b9/category HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bebidas",
  "is_active": true
}

###
GET http://localhost:8080/menu/categories/906809e1-25ae-40ce-91d5-af90313868b9 HTTP/1.1
Authorization: Bearer {{token}}

###
GET http://localhost:8080/menu/category/f6dfc2a0-a464-42ae-964c-5eeadcf68f2e HTTP/1.1
Authorization: Bearer {{token}}
