# @name login
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
  "email": "teste@gmail.com",
  "password": "123456"
}

@token = {{login.response.body.data.token}}

###
POST http://localhost:8080/menu/98d17502-8915-49dc-8304-73069db5f72f/category HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bebidas",
  "is_active": true
}

###
GET http://localhost:8080/menu/categories/33333333-3333-3333-3333-333333333333 HTTP/1.1
Authorization: Bearer {{token}}

###
GET http://localhost:8080/menu/category/44444444-4444-4444-4444-444444444444 HTTP/1.1
Authorization: Bearer {{token}}
