# @name login
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
  "email": "teste@gmail.com",
  "password": "123456"
}

@token = {{login.response.body.data.token}}

###
POST http://localhost:8080/menu/98d17502-8915-49dc-8304-73069db5f72f/category HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Bebidas",
  "is_active": true
}

###
GET http://localhost:8080/menu/categories/98d17502-8915-49dc-8304-73069db5f72f HTTP/1.1
Authorization: Bearer {{token}}

###
GET http://localhost:8080/menu/category/f6dfc2a0-a464-42ae-964c-5eeadcf68f2e HTTP/1.1
Authorization: Bearer {{token}}
