POST http://localhost:8080/stores/02a201bc-99a0-48af-9464-1f0adde0a8ea/menu HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3M2ZkMTZjYS04NDVlLTQ1ZTAtODg4Mi1iODkzNWM2Yzg3NjIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJzYWFzLWNvcmUiLCJleHAiOjE3NzA2ODQ1ODQsImlhdCI6MTc3MDU5ODE4NCwianRpIjoiZDI2OWE4YTYtZDdlOS00MjJkLTgyZGMtOGI1NzU4YTUzNWM4In0.wDTSS-b2AfV_P45WyVIaqeheG8IegQsb0-JVQ3SZKus

{
  "name": "Menu Principal",
  "isActive": true
}

###
GET http://localhost:8080/stores/menu/bd616188-7278-4b9d-b9d6-d0428d4f5939 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3M2ZkMTZjYS04NDVlLTQ1ZTAtODg4Mi1iODkzNWM2Yzg3NjIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJzYWFzLWNvcmUiLCJleHAiOjE3NzA2ODQ1ODQsImlhdCI6MTc3MDU5ODE4NCwianRpIjoiZDI2OWE4YTYtZDdlOS00MjJkLTgyZGMtOGI1NzU4YTUzNWM4In0.wDTSS-b2AfV_P45WyVIaqeheG8IegQsb0-JVQ3SZKus

###
GET http://localhost:8080/stores/02a201bc-99a0-48af-9464-1f0adde0a8ea/menu HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI3M2ZkMTZjYS04NDVlLTQ1ZTAtODg4Mi1iODkzNWM2Yzg3NjIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJzYWFzLWNvcmUiLCJleHAiOjE3NzA2ODQ1ODQsImlhdCI6MTc3MDU5ODE4NCwianRpIjoiZDI2OWE4YTYtZDdlOS00MjJkLTgyZGMtOGI1NzU4YTUzNWM4In0.wDTSS-b2AfV_P45WyVIaqeheG8IegQsb0-JVQ3SZKus
