POST http://localhost:8080/store HTTP/1.1
content-type: application/json

{
  "name": "Empresa Fantasia",
  "cnpj": "64.240.826/0001-00"
}

###
GET http://localhost:8080/store/7fcf5d42-bd42-4e2a-be6e-7b2a3e4bbf7e HTTP/1.1
