# @name login
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
  "email": "teste@gmail.com",
  "password": "123456"
}

@token = {{login.response.body.data.token}}

###
POST http://localhost:8080/store HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Empresa Fantasia",
  "cnpj": "64.240.826/0001-00"
}

###
GET http://localhost:8080/store/id/3096b57e-5d4c-4e75-875f-a57d1aafbeb7 HTTP/1.1
Authorization: Bearer {{token}}
