# @name login
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
  "email": "teste@gmail.com",
  "password": "123456"
}

@token = {{login.response.body.data.token}}

###
POST http://localhost:8080/store/3096b57e-5d4c-4e75-875f-a57d1aafbeb7/menu HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Menu Principal",
  "isActive": true
}

###
GET http://localhost:8080/store/3096b57e-5d4c-4e75-875f-a57d1aafbeb7/menus HTTP/1.1
Authorization: Bearer {{token}}

###
GET http://localhost:8080/menu/bd616188-7278-4b9d-b9d6-d0428d4f5939 HTTP/1.1
Authorization: Bearer {{token}}

