POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
  "name": "Nome Teste",
  "email": "teste@gmail.com",
  "password": "123456",
  
  "cpf": "856.081.860-01",
  "phone": "11999999999",
  "status": "active",
  "role": "admin"
}

###
GET http://localhost:8080/user/730edd37-5de8-4583-9e08-b4c91065d999 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhZmFlZjFkNS05YjAxLTQzZWItYjI2OC0wNmI5YTM2MWEzOTYiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJzYWFzLWNvcmUiLCJleHAiOjE3NzA2MzY1MDIsImlhdCI6MTc3MDU1MDEwMiwianRpIjoiMWQxOTJmM2EtNmE3MC00MDNlLWJlYzctNmRhODVhYzI2YzZlIn0.4X4aVIwRTaU5AykFxGL8mdccGu1D-OLo9POH23_lgXI

###
GET http://localhost:8080/user/email/teste@gmail.com HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhZmFlZjFkNS05YjAxLTQzZWItYjI2OC0wNmI5YTM2MWEzOTYiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJzYWFzLWNvcmUiLCJleHAiOjE3NzA2MzY1MDIsImlhdCI6MTc3MDU1MDEwMiwianRpIjoiMWQxOTJmM2EtNmE3MC00MDNlLWJlYzctNmRhODVhYzI2YzZlIn0.4X4aVIwRTaU5AykFxGL8mdccGu1D-OLo9POH23_lgXI

###
GET http://localhost:8080/user/cpf/856.081.860-01 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5NDk3ZTA0MS03OTU0LTQ2ZWUtYjBmZi03ZTg3NzI1MjczMDciLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJzYWFzLWNvcmUiLCJleHAiOjE3NzA2MzM0NzgsImlhdCI6MTc3MDU0NzA3OH0.Uc0IX__UVx7lylkBFxUnLBA8c8kUPuwwrrVrkSWq9iE



